CREATE TABLE pictures(
  PICTURE_ID INTEGER PRIMARY KEY NOT NULL,
  TOURNAMENT_ID INTEGER NOT NULL,
  PICTURE_DESCRIPTION TEXT,
  PICTURE_WIDTH INTEGER NOT NULL CONSTRAINT CHECK_POSITIVE_W CHECK (PICTURE_WIDTH > 0),
  PICTURE_HEIGHT INTEGER NOT NULL CONSTRAINT CHECK_POSITIVE_H CHECK (PICTURE_HEIGHT > 0),
  JPG_DATA BLOB NOT NULL,
  FOREIGN KEY(TOURNAMENT_ID) REFERENCES tournaments(TOURNAMENT_ID),
  CONSTRAINT CHECK_JPG_SIZE CHECK (length(JPG_DATA) <= 614400)
);
CREATE TABLE picture_tags(
  TAG_ID INTEGER PRIMARY KEY NOT NULL,
  PICTURE_ID INTEGER NOT NULL,
  TAG_X INTEGER NOT NULL CONSTRAINT CHECK_POSITIVE_TX CHECK (TAG_X >= 0),
  TAG_Y INTEGER NOT NULL CONSTRAINT CHECK_POSITIVE_TY CHECK (TAG_Y >= 0),
  TAG_SIZE INTEGER NOT NULL CONSTRAINT CHECK_POSITIVE_TS CHECK (TAG_SIZE > 0),
  PERSON_ID INTEGER NOT NULL,
  FOREIGN KEY(PICTURE_ID) REFERENCES pictures(PICTURE_ID),
  FOREIGN KEY(PERSON_ID) REFERENCES persons(PERSON_ID),
  UNIQUE(PICTURE_ID, PERSON_ID)
);
CREATE TABLE periods(
  PERIOD_ID INTEGER PRIMARY KEY NOT NULL,
  PERIOD_START TEXT NOT NULL CONSTRAINT CHECK_START_DATE CHECK ( --- YYYY-MM-DD
    PERIOD_START GLOB '[0-9][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9]'
  ),
  PERIOD_END TEXT NOT NULL CONSTRAINT CHECK_END_DATE CHECK ( --- YYYY-MM-DD
    PERIOD_END GLOB '[0-9][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9]'
  ),
  TABLE_CODE TEXT NOT NULL,
  LOCATION_CODE TEXT NOT NULL,
  PERIOD_COMMENT TEXT,
  FOREIGN KEY(TABLE_CODE) REFERENCES tables(TABLE_CODE)
  FOREIGN KEY(LOCATION_CODE) REFERENCES locations(LOCATION_CODE)
  UNIQUE(LOCATION_CODE, PERIOD_START)
);
CREATE TABLE locations(
  LOC_CODE TEXT PRIMARY KEY NOT NULL,
  LOCATION_NAME TEXT NOT NULL UNIQUE,
  LOCATION_CITY TEXT NOT NULL,
  LOCATION_STREET TEXT,
  LOCATION_STR_NUMBER INTEGER
);
CREATE TABLE brands(
  BRAND_CODE TEXT PRIMARY KEY NOT NULL,
  BRAND_NAME TEXT NOT NULL UNIQUE,
  BRAND_COUNTRY TEXT CONSTRAINT CHECK_CNTRY CHECK ( --- ISO 3166 Alpha-2 code,
    BRAND_COUNTRY GLOB '[A-Z][A-Z]'
  )
);
CREATE TABLE tables(
  BRAND_CODE TEXT, 
  TABLE_CODE TEXT PRIMARY KEY NOT NULL,
  TABLE_NAME TEXT NOT NULL UNIQUE,
  FOREIGN KEY(BRAND_CODE) REFERENCES brands(BRAND_CODE)
);
CREATE TABLE table_sides(
  SIDE_ID INTEGER PRIMARY KEY NOT NULL,
  SIDE TEXT
);
CREATE TABLE side_properties(
  SIDE_PROP_ID INTEGER PRIMARY KEY NOT NULL,
  SIDE_ID INTEGER NOT NULL,
  TABLE_CODE TEXT NOT NULL,
  COLOR_NAME TEXT NOT NULL,
  COLOR_RGB TEXT CONSTRAINT CHECK_COLOR CHECK (
    COLOR_RGB GLOB '#[0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F]'
  ),
  FOREIGN KEY(SIDE_ID) REFERENCES table_sides(SIDE_ID),
  FOREIGN KEY(TABLE_CODE) REFERENCES tables(TABLE_CODE),
  UNIQUE(TABLE_CODE, SIDE_ID)
);
CREATE TABLE roles(
  ROLE_CODE TEXT PRIMARY KEY NOT NULL,
  ROLE TEXT NOT NULL
);
CREATE TABLE positions(
  POSITION_CODE TEXT PRIMARY KEY NOT NULL, 
  ROLE_CODE TEXT NOT NULL,
  SIDE_ID INTEGER NOT NULL,
  PSEUDO_SIDE_ID INTEGER NOT NULL,
  POSITION TEXT NOT NULL,
  FOREIGN KEY(ROLE_CODE) REFERENCES roles(ROLE_CODE)
  FOREIGN KEY(SIDE_ID) REFERENCES table_sides(SIDE_ID)
  FOREIGN KEY(PSEUDO_SIDE_ID) REFERENCES table_sides(SIDE_ID), -- Side to use when the actual side is unknown
  UNIQUE(ROLE_CODE, SIDE_ID)
);
CREATE TABLE genders(
  GENDER_CODE TEXT PRIMARY KEY NOT NULL,
  GENDER TEXT NOT NULL
);
CREATE TABLE persons(
  PERSON_ID INTEGER PRIMARY KEY NOT NULL,
  PERSON_NAME TEXT NOT NULL UNIQUE,
  GENDER_CODE TEXT NOT NULL,
  QUALIFICATION_CODE TEXT NOT NULL,
  HOME_BASE TEXT,
  FOREIGN KEY(GENDER_CODE) REFERENCES genders(GENDER_CODE),
  FOREIGN KEY(QUALIFICATION_CODE) REFERENCES qualifications(QUALIFICATION_CODE),
  FOREIGN KEY(HOME_BASE) REFERENCES locations(LOC_CODE)
);
CREATE TABLE qualifications(
  QUALIFICATION_CODE TEXT PRIMARY KEY NOT NULL,
  QUALIFICATION TEXT NOT NULL UNIQUE,
  QUALIFICATION_RATIO REAL NOT NULL,
  QUALIFICATION_SUCCESS REAL NOT NULL,
  QUALIFICATION_DESCR TEXT
);
CREATE TABLE participants(
  PARTICIPANT_ID INTEGER PRIMARY KEY NOT NULL,
  TOURNAMENT_ID INTEGER NOT NULL,
  PERSON_ID INTEGER NOT NULL,
  PENALTY_POINTS INTEGER CONSTRAINT CHECK_POSITIVE_PENAL CHECK (PENALTY_POINTS >= 0),
  FOREIGN KEY(TOURNAMENT_ID) REFERENCES tournaments(TOURNAMENT_ID),
  FOREIGN KEY(PERSON_ID) REFERENCES persons(PERSON_ID),
  UNIQUE(TOURNAMENT_ID, PERSON_ID)
);
CREATE TABLE match_results(
  MATCH_ID INTEGER NOT NULL,
  RESULT INTEGER CONSTRAINT CHECK_POSITIVE_RESULT CHECK (RESULT >= 0),
  SIDE_ID INTEGER NOT NULL,
  FOREIGN KEY(MATCH_ID) REFERENCES matches(MATCH_ID),
  FOREIGN KEY(SIDE_ID) REFERENCES table_sides(SIDE_ID),
  UNIQUE(MATCH_ID, SIDE_ID)
);
CREATE TABLE match_players(
  MATCH_ID INTEGER NOT NULL,
  PARTICIPANT_ID INTEGER NOT NULL,
  POSITION_CODE TEXT NOT NULL,
  FOREIGN KEY(MATCH_ID) REFERENCES matches(MATCH_ID),
  FOREIGN KEY(PARTICIPANT_ID) REFERENCES participants(PARTICIPANT_ID)
  UNIQUE(MATCH_ID, PARTICIPANT_ID),
  UNIQUE(MATCH_ID, POSITION_CODE)
);
CREATE TABLE matches(
  MATCH_ID INTEGER PRIMARY KEY NOT NULL,
  TOURNAMENT_ID INTEGER NOT NULL,
  TOURN_PHASE_CODE TEXT NOT NULL,
  TABLE_CODE TEXT NOT NULL,
  BALL_ID INTEGER NOT NULL,
  FOREIGN KEY(TOURNAMENT_ID) REFERENCES tournaments(TOURNAMENT_ID),
  FOREIGN KEY(TOURN_PHASE_CODE) REFERENCES tournament_phases(TOURN_PHASE_CODE),
  FOREIGN KEY(TABLE_CODE) REFERENCES tables(TABLE_CODE),
  FOREIGN KEY(BALL_ID) REFERENCES balls(BALL_ID)
  UNIQUE(MATCH_ID, TOURNAMENT_ID)
);
CREATE TABLE balls(
  BALL_ID INTEGER PRIMARY KEY NOT NULL,
  BALL_DESCRIPTION TEXT NOT NULL UNIQUE
);
CREATE TABLE tournament_phase_flow(
  TOURN_TYPE_ID INTEGER NOT NULL,
  PHASE_ORDER INTEGER NOT NULL CONSTRAINT PHASE_ORDER_CHECK CHECK (
    PHASE_ORDER > 0
  ),
  TOURN_PHASE_CODE TEXT NOT NULL,
  IS_OPTIONAL INTEGER NOT NULL CONSTRAINT CHECK_IS_OPTIONAL CHECK(
    IS_OPTIONAL IN (0, 1)
  ),
  PRIMARY KEY(TOURN_TYPE_ID, PHASE_ORDER),
  FOREIGN KEY(TOURN_TYPE_ID) REFERENCES tournament_types(TOURN_TYPE_ID),
  FOREIGN KEY(TOURN_PHASE_CODE) REFERENCES tournament_phases(TOURN_PHASE_CODE)
);
CREATE TABLE tournament_types(
  TOURN_TYPE_ID INTEGER PRIMARY KEY NOT NULL,
  TOURNAMENT_TYPE TEXT NOT NULL UNIQUE
);
CREATE TABLE tournaments(
  TOURNAMENT_ID INTEGER PRIMARY KEY NOT NULL,
  TOURN_TYPE_ID INTEGER NOT NULL,
  TOURNAMENT_DATE TEXT CONSTRAINT CHECK_DATE CHECK ( --- YYYY-MM-DD
    TOURNAMENT_DATE GLOB '[0-9][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9]'
  ),
  TOURNAMENT_DURATION FLOAT CONSTRAINT CHECK_DURATION CHECK (
    TOURNAMENT_DURATION > 0
  ),
  POINT_SYSTEM_ID INTEGER,
  LOC_CODE TEXT,
  TOURNAMENT_STATE_CODE TEXT NOT NULL,
  TOURNAMENT_COMMENTS TEXT,
  FOREIGN KEY(LOC_CODE) REFERENCES locations(LOC_CODE),
  FOREIGN KEY(TOURN_TYPE_ID) REFERENCES tournament_types(TOURN_TYPE_ID),
  FOREIGN KEY(POINT_SYSTEM_ID) REFERENCES point_systems(POINT_SYSTEM_ID),
  FOREIGN KEY(TOURNAMENT_STATE_CODE) REFERENCES tournament_states(TOURNAMENT_STATE_CODE)
);
CREATE TABLE tournament_states(
  TOURNAMENT_STATE_CODE TEXT PRIMARY KEY NOT NULL,
  TOURNAMENT_STATE TEXT NOT NULL UNIQUE
);
CREATE TABLE point_systems(
  POINT_SYSTEM_ID INTEGER PRIMARY KEY NOT NULL,
  PS_DESCRIPTION TEXT NOT NULL,
  MAX_POINTS_PER_MATCH INTEGER NOT NULL
);
CREATE TABLE tournament_organisers(
  TOURNAMENT_ID INTEGER NOT NULL,
  PERSON_ID INTEGER NOT NULL,
  FOREIGN KEY(TOURNAMENT_ID) REFERENCES tournaments(TOURNAMENT_ID),
  FOREIGN KEY(PERSON_ID) REFERENCES persons(PERSON_ID),
  UNIQUE(TOURNAMENT_ID, PERSON_ID)
);
CREATE TABLE tournament_phases(
  TOURN_PHASE_CODE TEXT PRIMARY KEY NOT NULL,
  TOURNAMENT_PHASE TEXT NOT NULL,
  IS_NESTED INTEGER NOT NULL CONSTRAINT CHECK_NESTED CHECK(
    IS_NESTED IN (0, 1)
  )
);
CREATE VIEW match_positions AS
SELECT
       MATCH_ID,
       MIN(IIF(POSITION_CODE IN ('D1', 'U1', 'DU', 'UU'), PARTICIPANT_NAME, NULL)) PLAYER_DEFENSE_1,
       MAX(IIF(POSITION_CODE IN ('S1', 'U1', 'SU', 'UU'), PARTICIPANT_NAME, NULL)) PLAYER_STRIKE_1,
       MIN(IIF(POSITION_CODE IN ('D2', 'U2', 'DO', 'UO'), PARTICIPANT_NAME, NULL)) PLAYER_DEFENSE_2,
       MAX(IIF(POSITION_CODE IN ('S2', 'U2', 'SO', 'UO'), PARTICIPANT_NAME, NULL)) PLAYER_STRIKE_2
FROM match_players
LEFT JOIN (SELECT PARTICIPANT_ID,PARTICIPANT_NAME FROM participants_view) USING (PARTICIPANT_ID)
GROUP BY MATCH_ID;
CREATE VIEW participants_view AS
SELECT TOURNAMENT_ID,
       PARTICIPANT_ID,
       PERSON_NAME AS PARTICIPANT_NAME
FROM(
  SELECT * FROM participants
  LEFT JOIN (SELECT PERSON_ID, PERSON_NAME FROM persons) USING(PERSON_ID)
);
CREATE VIEW matches_view AS
SELECT TOURNAMENT_ID,
       TOURNAMENT_PHASE,
       MATCH_ID,
       PLAYER_DEFENSE_1,
       PLAYER_STRIKE_1,
       PLAYER_DEFENSE_2,
       PLAYER_STRIKE_2,
       MAX(IIF(PSEUDO_SIDE_ID='1', RESULT, NULL)) SCORE_1,
       MAX(IIF(PSEUDO_SIDE_ID='2', RESULT, NULL)) SCORE_2,
       TABLE_NAME,
       COLOR_NAME1,
       COLOR_RGB1,
       COLOR_NAME2,
       COLOR_RGB2
FROM (
  SELECT * FROM matches
  LEFT JOIN match_positions USING (MATCH_ID)
  LEFT JOIN tournament_phases USING(TOURN_PHASE_CODE)
  LEFT JOIN match_results USING(MATCH_ID)
  LEFT JOIN (SELECT SIDE_ID, PSEUDO_SIDE_ID FROM positions) USING (SIDE_ID)
  LEFT JOIN tables USING(TABLE_CODE)
  LEFT JOIN (SELECT TABLE_CODE,COLOR_NAME AS COLOR_NAME1,COLOR_RGB AS COLOR_RGB1 FROM side_properties WHERE SIDE_ID = '1') USING(TABLE_CODE)
  LEFT JOIN (SELECT TABLE_CODE,COLOR_NAME AS COLOR_NAME2,COLOR_RGB AS COLOR_RGB2 FROM side_properties WHERE SIDE_ID = '2') USING(TABLE_CODE)
)
GROUP BY MATCH_ID;
CREATE VIEW opponent_results AS
SELECT MATCH_ID, SIDE_ID, PSEUDO_SIDE_ID, RESULT, RESULT_OPPONENT,
     CASE SIGN(RESULT - RESULT_OPPONENT)
       WHEN 1 THEN 'WIN'
       WHEN 0 THEN 'DRAW'
       WHEN -1 THEN 'LOSE'
     END CONCLUSION,
     POINT_SYSTEM_ID,
     MAX_POINTS_PER_MATCH
FROM (
  SELECT * FROM(
    SELECT DISTINCT * FROM match_results
    LEFT JOIN (SELECT SIDE_ID, PSEUDO_SIDE_ID FROM positions) USING(SIDE_ID)
  ) AS m_r
  LEFT JOIN (
    SELECT PSEUDO_SIDE_ID, 3 - PSEUDO_SIDE_ID AS OPPOSIT_SIDE, RESULT AS RESULT_OPPONENT, MATCH_ID FROM (
      SELECT DISTINCT * FROM match_results
      LEFT JOIN (SELECT DISTINCT SIDE_ID, PSEUDO_SIDE_ID FROM positions) USING(SIDE_ID)
    ) 
  ) AS oppo ON oppo.OPPOSIT_SIDE=m_r.PSEUDO_SIDE_ID AND oppo.MATCH_ID=m_r.MATCH_ID
)
LEFT JOIN (SELECT TOURNAMENT_ID, MATCH_ID FROM matches) USING(MATCH_ID)
LEFT JOIN (SELECT TOURNAMENT_ID, POINT_SYSTEM_ID FROM tournaments) USING(TOURNAMENT_ID)
LEFT JOIN (SELECT POINT_SYSTEM_ID, MAX_POINTS_PER_MATCH FROM point_systems) USING(POINT_SYSTEM_ID)
ORDER BY MATCH_ID;
CREATE VIEW participant_match_results AS
SELECT DISTINCT
  TOURNAMENT_ID,
  TOURNAMENT_DATE,
  LOCATION_NAME,
  LOCATION_CITY,
  TOURNAMENT_PHASE,
  mp.MATCH_ID,
  PARTICIPANT_ID,
  POSITION_CODE,
  ROLE_CODE,
  mp.SIDE_ID,
  PERSON_ID,
  PERSON_NAME AS PARTICIPANT,
  RESULT,
  RESULT_OPPONENT,
  PENALTY_POINTS,
  CONCLUSION,
  CASE TOURNAMENT_PHASE
    WHEN 'Qualification' THEN (
      CASE POINT_SYSTEM_ID
        WHEN 1 THEN (
          CASE CONCLUSION
            WHEN 'WIN' THEN 3
            WHEN 'DRAW' THEN 1
            ELSE 0
          END
        )
        WHEN 2 THEN RESULT - PENALTY_POINTS
        ELSE NULL
      END
    ) ELSE (
      IIF(CONCLUSION='WIN', 1, 0)
    )
  END MATCH_POINTS,
  (IIF(
    RESULT = 0 AND RESULT_OPPONENT = 0,
    0.5,
    CAST(RESULT AS FLOAT)/CAST((RESULT + RESULT_OPPONENT) AS FLOAT)
  )) AS SUCCESS_RATE
FROM (
  SELECT
    MATCH_ID,
    PARTICIPANT_ID,
    POSITION_CODE,
    ROLE_CODE,
    SIDE_ID,
    TOURN_PHASE_CODE
  FROM participants
  LEFT JOIN (
    SELECT DISTINCT
      MATCH_ID,
      PARTICIPANT_ID,
      POSITION_CODE,
      ROLE_CODE,
      SIDE_ID,
      TOURN_PHASE_CODE
    FROM match_players
    LEFT JOIN positions USING(POSITION_CODE)
    LEFT JOIN (SELECT MATCH_ID, TOURNAMENT_ID, TOURN_PHASE_CODE FROM matches) USING(MATCH_ID)
  ) USING(PARTICIPANT_ID)
) AS mp
LEFT JOIN (SELECT MATCH_ID, SIDE_ID, RESULT, RESULT_OPPONENT, POINT_SYSTEM_ID, CONCLUSION FROM opponent_results) AS o_r
  ON mp.MATCH_ID = o_r.MATCH_ID AND mp.SIDE_ID = o_r.SIDE_ID
LEFT JOIN participants USING(PARTICIPANT_ID)
LEFT JOIN persons USING(PERSON_ID)
LEFT JOIN tournament_phases USING(TOURN_PHASE_CODE)
LEFT JOIN (SELECT TOURNAMENT_ID, TOURNAMENT_DATE, LOC_CODE FROM tournaments) USING(TOURNAMENT_ID)
LEFT JOIN (SELECT LOCATION_NAME, LOC_CODE, LOCATION_CITY FROM locations) USING (LOC_CODE);
CREATE VIEW participant_tournament_results AS
SELECT TOURNAMENT_ID, TOURNAMENT_PHASE, TOURNAMENT_DATE, LOCATION_CITY, MAX_POINTS_PER_MATCH, PERSON_ID, PARTICIPANT_ID,
  PARTICIPANT, PARTICIPANT_HOME, PENALTY_POINTS, RESULT, RESULT_OPPONENT, WINS, LOSSES, DRAWS, MATCHES_PLAYED, TOTAL_MATCHES,
  (TOTAL_MATCHES - MATCHES_PLAYED)*MAX_POINTS_PER_MATCH AS REMAINING_POINTS,
  (TOTAL_MATCHES - MATCHES_PLAYED)*MAX_POINTS_PER_MATCH + IIF(TOURNAMENT_POINTS IS NULL, 0, TOURNAMENT_POINTS) AS POTENTIAL_POINTS,
  IIF(TOURNAMENT_POINTS IS NULL, 0, TOURNAMENT_POINTS) AS TOURNAMENT_POINTS,
  RANK () OVER (
		PARTITION BY TOURNAMENT_ID, TOURNAMENT_PHASE
		ORDER BY ((TOTAL_MATCHES - MATCHES_PLAYED)*MAX_POINTS_PER_MATCH + IIF(TOURNAMENT_POINTS IS NULL, 0, TOURNAMENT_POINTS)) DESC
	) POTENTIAL_RANK,
  RANK () OVER (
		PARTITION BY TOURNAMENT_ID, TOURNAMENT_PHASE
		ORDER BY TOURNAMENT_POINTS DESC
	) TOURNAMENT_RANK
FROM (
  SELECT
    TOURNAMENT_ID,
    TOURNAMENT_PHASE,
    TOURNAMENT_DATE,
    LOCATION_CITY,
    MAX_POINTS_PER_MATCH,
    PERSON_ID,
    PARTICIPANT_ID,
    PARTICIPANT,
    PENALTY_POINTS,
    SUM(RESULT) AS RESULT,
    SUM(RESULT_OPPONENT) AS RESULT_OPPONENT,
    SUM(IIF(CONCLUSION = 'WIN', 1, 0)) AS WINS,
    SUM(IIF(CONCLUSION = 'LOSE', 1, 0)) AS LOSSES,
    SUM(IIF(CONCLUSION = 'DRAW', 1, 0)) AS DRAWS,
    CASE POINT_SYSTEM_ID
      WHEN 1 THEN CAST(SUM(MATCH_POINTS) - PENALTY_POINTS AS FLOAT) + 0.9*AVG(SUCCESS_RATE)
      WHEN 2 THEN CAST(SUM(MATCH_POINTS) - PENALTY_POINTS AS FLOAT) + 1.0 - CAST(SUM(RESULT_OPPONENT) AS FLOAT)/(10.0*CAST(COUNT(MATCH_ID) AS FLOAT))
      ELSE NULL
    END TOURNAMENT_POINTS,
    SUM(IIF(RESULT IS NULL OR RESULT_OPPONENT IS NULL, 0, 1)) AS MATCHES_PLAYED,
    COUNT(MATCH_ID) AS TOTAL_MATCHES
  FROM participant_match_results
  LEFT JOIN (SELECT POINT_SYSTEM_ID, TOURNAMENT_ID, LOC_CODE FROM tournaments) USING (TOURNAMENT_ID)
  LEFT JOIN (SELECT POINT_SYSTEM_ID, MAX_POINTS_PER_MATCH FROM point_systems) USING(POINT_SYSTEM_ID)
  GROUP BY TOURNAMENT_ID, TOURNAMENT_PHASE, PARTICIPANT_ID
)
LEFT JOIN (
  SELECT * FROM (
    SELECT PERSON_NAME PARTICIPANT, HOME_BASE FROM persons
  ) LEFT JOIN (SELECT LOC_CODE HOME_BASE, LOCATION_CITY PARTICIPANT_HOME FROM locations) USING(HOME_BASE)
) USING(PARTICIPANT)
ORDER BY TOURNAMENT_ID, TOURNAMENT_PHASE, TOURNAMENT_RANK;
CREATE VIEW player_statistics AS
SELECT DISTINCT
PERSON_ID,
QUALIFICATION_CODE,
PARTICIPANT,
TOURNAMENT_PHASE,
SUM(RESULT) AS GOALS_SCORED,
SUM(RESULT_OPPONENT) AS GOALS_CONCEDED,
CAST(SUM(RESULT) AS FLOAT)/CAST(SUM(RESULT_OPPONENT) AS FLOAT) AS GOAL_RATIO,
CAST(SUM(RESULT) AS FLOAT)/CAST((SUM(RESULT_OPPONENT) + SUM(RESULT)) AS FLOAT) AS SUCCESS_RATE,
IIF(QUALIFICATION_CODE='H', IIF(RESULT IS NULL, 0.5, CAST(SUM(RESULT) AS FLOAT)/CAST((SUM(RESULT_OPPONENT) + SUM(RESULT)) AS FLOAT)), QUALIFICATION_SUCCESS) AS QUALIFICATION_RATE,
IIF(TOURNAMENT_PHASE='Final', COUNT(DISTINCT IIF(CONCLUSION='WIN', TOURNAMENT_ID, NULL)), NULL) AS CHAMPION_COUNT,
IIF(TOURNAMENT_PHASE='Final', COUNT(DISTINCT IIF(CONCLUSION='LOSE', TOURNAMENT_ID, NULL)), NULL) AS RUNNERUP_COUNT,
COUNT(DISTINCT MATCH_ID) AS MATCHES_PLAYED,
COUNT(DISTINCT TOURNAMENT_ID) AS TOURNAMENTS_PLAYED,
COUNT(DISTINCT LOCATION_CITY) AS CITIES_PLAYED
FROM participant_match_results
LEFT JOIN (SELECT QUALIFICATION_CODE, PERSON_ID FROM persons) USING(PERSON_ID)
LEFT JOIN (SELECT QUALIFICATION_CODE, QUALIFICATION_SUCCESS FROM qualifications) USING(QUALIFICATION_CODE)
GROUP BY PERSON_ID, TOURNAMENT_PHASE
ORDER BY TOURNAMENT_PHASE, PARTICIPANT;
CREATE VIEW tournaments_view AS
SELECT
  TOURNAMENT_ID,
  TOURNAMENT_DATE,
  TOURNAMENT_STATE,
  ORGANISERS,
  POINT_SYSTEM_ID,
  TOURNAMENT_DURATION,
  LOCATION_NAME AS LOCATION,
  COUNT(DISTINCT PARTICIPANT_ID) AS NUMBER_OF_PARTICIPANTS,
  COUNT(DISTINCT MATCH_ID) AS NUMBER_OF_MATCHES,
  COUNT(DISTINCT MATCH_PLAYED) AS MATCHES_PLAYED,
  PARTICIPANT AS CHAMPION
FROM tournaments
LEFT JOIN tournament_states USING(TOURNAMENT_STATE_CODE)
LEFT JOIN participants USING(TOURNAMENT_ID)
-- Select Qualification matches only:
LEFT JOIN (SELECT DISTINCT MATCH_ID, TOURNAMENT_ID FROM matches WHERE TOURN_PHASE_CODE = 'Q') USING (TOURNAMENT_ID)
LEFT JOIN locations USING(LOC_CODE)
LEFT JOIN (SELECT TOURNAMENT_ID,PARTICIPANT FROM participant_match_results WHERE TOURNAMENT_PHASE = 'Final' AND CONCLUSION = 'WIN') USING(TOURNAMENT_ID)
LEFT JOIN (SELECT TOURNAMENT_ID, MATCH_ID AS MATCH_PLAYED FROM matches_view WHERE SCORE_1 IS NOT NULL AND SCORE_2 IS NOT NULL AND TOURNAMENT_PHASE = 'Qualification') USING(TOURNAMENT_ID)
LEFT JOIN (
  SELECT TOURNAMENT_ID,GROUP_CONCAT(PERSON_NAME, '; ') ORGANISERS FROM tournament_organisers
  LEFT JOIN persons USING(PERSON_ID)
  GROUP BY TOURNAMENT_ID
) USING (TOURNAMENT_ID)
GROUP BY TOURNAMENT_ID
ORDER BY TOURNAMENT_DATE;
CREATE VIEW table_statistics AS
SELECT *,
  IIF (SCORE_1=0 AND SCORE_2=0, 0.5,
    CAST(SCORE_1 AS FLOAT)/(CAST(SCORE_1 AS FLOAT) + CAST(SCORE_2 AS FLOAT))) AS SUCCESS_RATE,
  IIF (SCORE_U1=0 AND SCORE_U2=0, 0.5,
    CAST(SCORE_U1 AS FLOAT)/(CAST(SCORE_U1 AS FLOAT) + CAST(SCORE_U2 AS FLOAT))) AS SUCCESS_RATE_U
FROM (
  SELECT DISTINCT MATCH_ID, TOURNAMENT_ID, TOURNAMENT_PHASE, TABLE_NAME,
    MAX(CASE WHEN SIDE = 'One' THEN RESULT ELSE NULL END) SCORE_1,
    MAX(CASE WHEN SIDE = 'Two' THEN RESULT ELSE NULL END) SCORE_2,
    MAX(CASE WHEN SIDE = 'Unknown' THEN RESULT ELSE NULL END) SCORE_U1,
    MAX(CASE WHEN SIDE = 'Unknown opposed' THEN RESULT ELSE NULL END) SCORE_U2
  FROM (
    SELECT * FROM match_results
    LEFT JOIN matches USING(MATCH_ID)
    LEFT JOIN tournaments USING(TOURNAMENT_ID)
    LEFT JOIN tournament_phases USING(TOURN_PHASE_CODE)
    LEFT JOIN tables USING (TABLE_CODE)
    LEFT JOIN table_sides USING (SIDE_ID)
  ) GROUP BY MATCH_ID
);
CREATE VIEW table_summary AS
SELECT * FROM tables
LEFT JOIN (
  SELECT
    TABLE_NAME,
    SUM(SCORE_1) AS SCORED_SIDE_1,
    SUM(SCORE_2) AS SCORED_SIDE_2,
    SUM(SCORE_U1) AS SCORED_SIDE_U1,
    SUM(SCORE_U2) AS SCORED_SIDE_U2,
    AVG(SUCCESS_RATE) AS SUCCESS_RATE,
    COUNT(DISTINCT MATCH_ID) AS MATCHES_PLAYED,
    COUNT(DISTINCT TOURNAMENT_ID) AS TOURNAMENTS_PLAYED
  FROM table_statistics
  GROUP BY TABLE_NAME
) USING(TABLE_NAME);
CREATE VIEW picture_tag_names AS
SELECT * FROM picture_tags
LEFT JOIN (SELECT PERSON_NAME, PERSON_ID FROM persons) USING(PERSON_ID);
CREATE VIEW player_combos AS
SELECT PLAYER_1, PLAYER_2, COMBI, TOURNAMENT_ID, TOURN_PHASE_CODE, COUNT(DISTINCT MATCH_ID) TIMES FROM (
  SELECT * FROM (
    SELECT MATCH_ID, PLAYER_DEFENSE_1 PLAYER_1, PLAYER_DEFENSE_2 PLAYER_2, 'DoD' COMBI FROM match_positions
    UNION ALL
    SELECT MATCH_ID, PLAYER_DEFENSE_1 PLAYER_1, PLAYER_STRIKE_2 PLAYER_2, 'DoS' COMBI FROM match_positions
    UNION ALL
    SELECT MATCH_ID, PLAYER_DEFENSE_1 PLAYER_1, PLAYER_STRIKE_1 PLAYER_2, 'DwS' COMBI FROM match_positions
    UNION ALL
    SELECT MATCH_ID, PLAYER_STRIKE_1 PLAYER_1, PLAYER_DEFENSE_2 PLAYER_2, 'SoD' COMBI FROM match_positions
    UNION ALL
    SELECT MATCH_ID, PLAYER_STRIKE_1 PLAYER_1, PLAYER_STRIKE_2 PLAYER_2, 'SoS' COMBI FROM match_positions
    UNION ALL
    SELECT MATCH_ID, PLAYER_STRIKE_1 PLAYER_1, PLAYER_DEFENSE_1 PLAYER_2, 'SwD' COMBI FROM match_positions
    UNION ALL
    SELECT MATCH_ID, PLAYER_DEFENSE_2 PLAYER_1, PLAYER_DEFENSE_1 PLAYER_2, 'DoD' COMBI FROM match_positions
    UNION ALL
    SELECT MATCH_ID, PLAYER_DEFENSE_2 PLAYER_1, PLAYER_STRIKE_1 PLAYER_2, 'DoS' COMBI FROM match_positions
    UNION ALL
    SELECT MATCH_ID, PLAYER_DEFENSE_2 PLAYER_1, PLAYER_STRIKE_2 PLAYER_2, 'DwS' COMBI FROM match_positions
    UNION ALL
    SELECT MATCH_ID, PLAYER_STRIKE_2 PLAYER_1, PLAYER_DEFENSE_1 PLAYER_2, 'SoD' COMBI FROM match_positions
    UNION ALL
    SELECT MATCH_ID, PLAYER_STRIKE_2 PLAYER_1, PLAYER_STRIKE_1 PLAYER_2, 'SoS' COMBI FROM match_positions
    UNION ALL
    SELECT MATCH_ID, PLAYER_STRIKE_2 PLAYER_1, PLAYER_DEFENSE_2 PLAYER_2, 'SwD' COMBI FROM match_positions
  ) LEFT JOIN matches USING(MATCH_ID)
) WHERE NOT PLAYER_1 = PLAYER_2 GROUP BY TOURNAMENT_ID, TOURN_PHASE_CODE, PLAYER_1, PLAYER_2, COMBI;
PRAGMA journal_mode=WAL;
